CREATE OR REPLACE VIEW MYCLOSET
AS SELECT ROW_NUMBER() OVER(PARTITION BY MEMBER_NO ORDER BY TYPE_OPTION ASC, LIKE_STATUS DESC, CHANGE_DATE DESC) CNUM, A.*
FROM(SELECT CLOTH_NO, MEMBER_NO, TYPE_CODE, TYPE_OPTION, STYLE_CODE, COLOUR_CODE, FIT_CODE, SEASON_CODE, CLOTH_NAME, CLOTH_BUYDATE, CLOTH_MEMO, CLOTH_STATUS, LIKE_STATUS, CHANGE_DATE
FROM CLOSET
JOIN TYPE USING(TYPE_CODE)
WHERE CLOTH_STATUS = 'Y'
ORDER BY CLOTH_NO DESC)A;