DROP TABLE "TYPE";

CREATE TABLE "TYPE" (
	"TYPE_CODE"	VARCHAR2(20)		NOT NULL,
	"TYPE_NAME"	VARCHAR2(30)		NULL,
	"TYPE_OPTION" NUMBER NOT NULL
);

INSERT INTO TYPE VALUES('TSHIRTS', '반팔티', 1);
INSERT INTO TYPE VALUES('MANTOMAN', '맨투맨', 1);
INSERT INTO TYPE VALUES('HOOD', '후드티', 1);
INSERT INTO TYPE VALUES('KNIT', '니트', 1);
INSERT INTO TYPE VALUES('CARDIGAN', '가디건', 1);
INSERT INTO TYPE VALUES('PADDING', '패딩', 1);
INSERT INTO TYPE VALUES('JACKET', '자켓', 1);
INSERT INTO TYPE VALUES('BLOUSE', '원피스', 1);
INSERT INTO TYPE VALUES('COTTON', '면바지', 2);
INSERT INTO TYPE VALUES('JEAN', '청바지', 2);
INSERT INTO TYPE VALUES('SSKIRT', '짧은치마', 2);
INSERT INTO TYPE VALUES('LSKIRT', '긴치마', 2);
INSERT INTO TYPE VALUES('CAP', '모자', 3);
INSERT INTO TYPE VALUES('SCARF', '목도리', 3);
INSERT INTO TYPE VALUES('SNEAKERS', '스니커즈', 3);
INSERT INTO TYPE VALUES('DRESSSHOES', '구두', 3);
INSERT INTO TYPE VALUES('SANDAL', '샌들', 3);

COMMENT ON COLUMN TYPE.TYPE_CODE IS '타입코드';
COMMENT ON COLUMN TYPE.TYPE_NAME IS '타입이름';
COMMENT ON COLUMN TYPE.TYPE_OPTION IS '타입분류';

ALTER TABLE "TYPE" ADD CONSTRAINT "PK_TYPE" PRIMARY KEY (
	"TYPE_CODE"
);