-- VIEW QLIST 추가 구문 (수정 19.11.10.)
CREATE OR REPLACE VIEW QLIST
AS SELECT ROWNUM RNUM, A.*
FROM(SELECT QNA_NO, MEMBER_NICK, ENROLL_DATE, QNA_TITLE, QNA_CONTENTS, ANSWER_STATUS, ANSWER_CONTENTS  
FROM QNA
JOIN MEMBER USING (MEMBER_NO)
ORDER BY QNA_NO DESC)A;
