CREATE OR REPLACE VIEW SEARCH
AS SELECT ROWNUM RNUM, A.*
FROM(SELECT MEMBER_NO, ARTICLE_NO, ARTICLE_VIEWS, ARTICLE_WISHES, ARTICLE_CONTENTS, MEMBER_NICK, PROFILE, LIKE_STYLE
FROM BOARD
JOIN MEMBER USING(MEMBER_NO)
ORDER BY ARTICLE_NO DESC)A;