-- VIEW QLIST 추가 구문 (수정 19.11.07)
CREATE OR REPLACE VIEW QLIST
AS SELECT ROWNUM RNUM, A.*
FROM(SELECT QNA_NO, QNA_TITLE, MEMBER_NICK, ENROLL_DATE, ANSWER_STATUS,QNA_CONTENTS, ANSWER_CONTENTS  
FROM QNA
JOIN MEMBER USING (MEMBER_NO)
ORDER BY QNA_NO DESC)A;


