-- ADM 스타일게시판관리 리스트조회용 VIEW (+ 19.11.10. 일부 컬럼추가 : PROFILE, LIKE_STYLE, ARTICLE_STATUS)
CREATE OR REPLACE VIEW BLIST
AS SELECT ROWNUM RNUM, A.*
FROM(SELECT ARTICLE_NO, MEMBER_NICK, PROFILE, LIKE_STYLE, ARTICLE_VIEWS, 
ARTICLE_WISHES, ARTICLE_CONTENTS, ARTICLE_DATE, ARTICLE_STATUS
FROM BOARD
JOIN MEMBER USING (MEMBER_NO)
ORDER BY ARTICLE_NO DESC)A;


