-- BOARD 테이블엥 COLUMN : MEMBER_NICK 추가
ALTER TABLE BOARD ADD (MEMBER_NICK VARCHAR2(60));

-- ADM 스타일게시판관리 리스트조회용 VIEW
CREATE OR REPLACE VIEW BLIST
AS SELECT ROWNUM RNUM, A.*
FROM(SELECT ARTICLE_NO, ARTICLE_CONTENTS, MEMBER_NICK, ARTICLE_DATE, ARTICLE_WISHES, ARTICLE_VIEWS 
FROM BOARD
ORDER BY ARTICLE_NO DESC)A;

-- MYBLIST 구문 삭제 및 새로 추가 (create_MYBLIST에서 계속)