-- VIEW QLIST 추가 구문
CREATE OR REPLACE VIEW QLIST
AS SELECT ROWNUM RNUM, A.*
FROM(SELECT QNA_NO, QNA_TITLE, MEMBER_NICK, ENROLL_DATE, ANSWER_STATUS 
FROM QNA
JOIN MEMBER USING (MEMBER_NO)
ORDER BY QNA_NO DESC)A;

