-- QNA 테이블에 COLUMN : MEMBER_NICK 추가
ALTER TABLE QNA ADD (MEMBER_NICK VARCHAR2(60));

-- VIEW QLIST 추가 구문
CREATE OR REPLACE VIEW QLIST
AS SELECT ROWNUM RNUM, A.*
FROM(SELECT QNA_NO, QNA_TITLE, MEMBER_NICK, ENROLL_DATE, ANSWER_STATUS 
FROM QNA
ORDER BY QNA_NO DESC)A;

-- MYQNALIST 구문 삭제 및 새로 추가 (create_MYQNALIST에서 계속)
