-- 기존 MYBLIST 삭제
DROP VIEW MYBLIST;

-- MEMBER_NICK 컬럼을 추가함으로써 JOIN 구문은 생략했음
CREATE OR REPLACE VIEW MYBLIST
AS SELECT ROW_NUMBER() OVER(PARTITION BY MEMBER_NO ORDER BY MEMBER_NO, ARTICLE_NO DESC) NUM, A.*
FROM(SELECT ARTICLE_NO, MEMBER_NO, MEMBER_NICK, ARTICLE_VIEWS, ARTICLE_WISHES, ARTICLE_URL, ARTICLE_CONTENTS, ARTICLE_DATE, ARTICLE_STATUS
FROM BOARD
WHERE ARTICLE_STATUS='Y'
ORDER BY ARTICLE_NO DESC)A;